### PR TITLE
Fix HomeScreen buttons

### PR DESCRIPTION
**Pull request by mangocat**
Disable the buttons if the phone does not support WiFi STA/AP concurrency and the other service is running.

### CODE REVIEW

**Comment by ccameron-gb** [comment]
I believe this is the Notion task related to this PR:
https://www.notion.so/grey-box/Modify-HomeScreen-buttons-to-be-aware-of-Wi-Fi-STA-AP-concurrency-support-10a815ddf30b80e58ac9f41759a4aa49?pvs=4

**Comment by mangocat** [comment]
Yes, it is.

**Review by kelvinlin9614 — APPROVED** [review]
Great job! I had been thinking about this part too, but I ended up using the default "True" since I couldn't come up with proper logic for enabling or disabling the button.

**Comment by ccameron-gb** [comment]
There's some question about handling Android 9 and 10 phones who don't seem able to report STA/AP concurrency support. We'll leave that as a future task (See: https://www.notion.so/grey-box/Investigate-the-role-of-STA-concurrency-with-the-ability-to-operate-as-hotspot-and-client-simultaneo-10f815ddf30b80bbaedaeca6a2649e97?pvs=4)

**Pull request merged**
